
WITH ReviewCount AS (
    SELECT 
        MEMBER_ID,
        COUNT(*) AS REVIEW_COUNT
    FROM 
        REST_REVIEW R
    GROUP BY MEMBER_ID
), 
MaxReviewer AS (
    SELECT MEMBER_ID
    FROM ReviewCount
    WHERE REVIEW_COUNT = (SELECT MAX(REVIEW_COUNT) FROM ReviewCount)
)

SELECT
    M.MEMBER_NAME AS MEMBER_NAME,
    R.REVIEW_TEXT AS REVIEW_TEXT,
    DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE 

FROM
    REST_REVIEW R
JOIN
    MEMBER_PROFILE M
    ON R.MEMBER_ID = M.MEMBER_ID
JOIN 
    MaxReviewer MR 
    ON R.MEMBER_ID = MR.MEMBER_ID

ORDER BY
    R.REVIEW_DATE ASC,
    R.REVIEW_TEXT ASC