WITH REVIEW_COUNT AS (
    SELECT 
        MEMBER_ID,
        COUNT(*) AS CNT
    FROM 
        REST_REVIEW
    GROUP BY
        MEMBER_ID
), 
MAX_REVIEWER AS (
    SELECT
        MEMBER_ID
    FROM
        REVIEW_COUNT
    WHERE
        CNT = (SELECT MAX(CNT) FROM REVIEW_COUNT)
)

SELECT
    M.MEMBER_NAME,
    R.REVIEW_TEXT,
    DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d')
FROM
    REST_REVIEW R
INNER JOIN
    MAX_REVIEWER MR
    ON MR.MEMBER_ID = R.MEMBER_ID
JOIN
    MEMBER_PROFILE M
    ON M.MEMBER_ID = R.MEMBER_ID

ORDER BY R.REVIEW_DATE ASC , R.REVIEW_TEXT ASC
