SELECT
    F.ID AS ID,
    N.FISH_NAME AS FISH_NAME, 
    F.LENGTH AS LENGTH
FROM FISH_INFO F
INNER JOIN FISH_NAME_INFO N
    ON F.FISH_TYPE = N.FISH_TYPE
WHERE (F.FISH_TYPE, F.LENGTH) IN (
    SELECT FISH_TYPE, MAX(LENGTH)
    FROM FISH_INFO
    WHERE LENGTH > 10
    GROUP BY FISH_TYPE
)
ORDER BY F.ID ASC; 